version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: jewelrystore_db
    environment:
      POSTGRES_DB: jewelrystore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - jewelrystore_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: jewelrystore_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - jewelrystore_network
    restart: unless-stopped
    depends_on:
      - postgres

networks:
  jewelrystore_network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data: